### PR TITLE
Update ReadMe + update to .NetFramework472

### LINKED ISSUE #50: Compliance issue for CSProj files
The following issues have been found for Unreal_Toolkit\Unreal_Adapter\Unreal_Adapter.csproj
 - [ ] Project references for 'Acoustic_oM' should be set to NOT copy local
 - [ ] Project references for 'Geometry_oM' should be set to NOT copy local

### LINKED ISSUE #51: Compliance issue for CSProj files
The following issues have been found for Unreal_Toolkit\Unreal_Engine\Unreal_Engine.csproj
 - [ ] Project references for 'Acoustic_oM' should be set to NOT copy local
 - [ ] Project references for 'Geometry_Engine' should be set to NOT copy local
 - [ ] Project references for BHoM DLLs should not include Version, Culture, or Processor Architecture

### LINKED ISSUE #52: Compliance issue for CSProj files
The following issues have been found for Unreal_Toolkit\Unreal_oM\Unreal_oM_Engine\Unreal_oM.csproj
 - [ ] Project references for 'Acoustic_oM' should be set to '..\..\BHoM\Build\Acoustic_oM.dll'
 - [ ] Project references for 'Acoustic_oM' should be set to NOT copy local
 - [ ] Project references for 'Geometry_oM' should be set to '..\..\BHoM\Build\Geometry_oM.dll'
 - [ ] Project references for 'Geometry_oM' should be set to NOT copy local

### LINKED ISSUE #73: Installer link needs updating?
#### What is missing/incorrect?

On the read me. Links here: https://bhom.xyz/assets/installers/v2.1/BHoM%20Alpha%20v2.1.0.5%20Installer.exe

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #50 
Fixes #51 
Fixes #52 
Fixes #73

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix project file ref. 4095685145

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project-compliance

**Review by emilsvedjer — APPROVED** [review]
LGTM

**Pull request merged**
